language: python
sudo: required
python:
  - "2.7"
install:
  - sudo apt-get update
  - sudo apt-get -y install python python-pip
  - pip install -r requirements.txt
script:
  - pytest -v
notifications:
  email: false
